name: 🐞 Bug Report
description: Report a reproducible bug.
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the info below.
  - type: input
    id: env
    attributes:
      label: Environment
      description: e.g., OS, Node version, browser
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe steps to reproduce
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
